defaults:
  - train_batch_preprocess: null
  - network: dit
  - loss: MSE
  - optimizer: adamw
  - lr_scheduler: warmup_cosine_decay
  - ema: constant

name: HoMMClsDiff
instance:
  _target_: model.diffusion.DiffusionModule
  model: ${model.network}
  mode: "eps"
  loss: ${model.loss}
  optimizer_cfg: ${model.optimizer}
  lr_scheduler_builder: ${model.lr_scheduler}
  torch_compile: false
  latent_encode: false
  latent_decode: false
  ema_cfg: ${model.ema}

