defaults:
  - train_batch_preprocess: null
  - network: dit
  - loss: MSE
  - optimizer: adam
  - lr_scheduler: warmup
  - sampler: ddim

name: HoMMClsDiff
instance:
  _target_: model.diffusion.DiffusionModule
  model: ${model.network}
  mode: "eps"
  val_sampler: ${model.sampler}
  loss: ${model.loss}
  optimizer_cfg: ${model.optimizer}
  lr_scheduler_builder: ${model.lr_scheduler}

