dataset: 
  name: cora
training_args:
  device: cpu
  n_gpus: 1
hyperp_model:
  n_layers: 2
  order: 2
  order_expand: 2
  ffw_expand: 2
  dropout: 0.0
hyperp_training:
  learning_rate: .0001
  weight_decay: 0
  n_epochs: 35
