_target_: model.network.imagediffusion.ClassConditionalDiT
n_classes: ${data.num_classes}
n_timesteps: 1000
dim: 256
im_size: ${data.size}
kernel_size: 8
n_layers: 8
order: 4
order_expand: 4
ffw_expand: 4
dropout: 0.0