_target_: model.network.imagediffusion.ClassConditionalDiH
n_classes: ${data.num_classes}
n_timesteps: 1000
input_dim: 4
dim: 1024
im_size: ${data.size}
kernel_size: 2
n_layers: 24
order: 2
order_expand: 2
ffw_expand: 2
dropout: 0.0