_target_: model.network.videodiffusion.TextVideoDiH
n_timesteps: 1000
input_dim: 16
text_dim: 1024
dim: 1152
vid_size: ${data.size}
vid_length: ${data.length}
kernel_s: 2
kernel_t: 2
n_layers: 20
order: 2
order_expand: 2
ffw_expand: 2