_target_: model.network.videodiffusion.TextVideoDiH
n_timesteps: 1000
input_dim: 128
text_dim: 2304
dim: 768
vid_size: ${data.size}
vid_length: ${data.length}
kernel_s: 1
kernel_t: 1
n_layers: 12
order: 2
order_expand: 2
ffw_expand: 3